### ISSUE TITLE
Website appears fubar

### ISSUE THREAD

**Issue by mccrispy** [SteveBallantine/spirit-island-randomiser#31]
I get "an unrelated error has occurred. Reload". Page displays "header" and "footer", but the body just says "loading"

**Comment by josephlambrecht** [comment]
Additional detail from console logs:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No item factory specified for 'SpiritAspect'
System.Exception: No item factory specified for 'SpiritAspect'
   at SiRandomizer.Data.OverallConfiguration.TakeSettingsFrom[SpiritAspect,SpiritAspect](IComponentCollection`1 destination, IComponentCollection`1 source, ILogger logger, Func`2 itemFactory)
   at SiRandomizer.Data.OverallConfiguration.TakeSettingsFrom[SpiritAspect](IComponentCollection`1 destination, IComponentCollection`1 source, ILogger logger)
   at SiRandomizer.Data.OverallConfiguration.TakeSettingsFrom[Spirit,SpiritAspect](IComponentCollection`1 destination, IComponentCollection`1 source, ILogger logger, Func`2 itemFactory)
   at SiRandomizer.Data.OverallConfiguration.TakeSettingsFrom(OverallConfiguration other, ILogger logger)
   at SiRandomizer.Services.PresetService.InitialisePresetsAsync()
   at SiRandomizer.Pages.Index.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

**Comment by josephlambrecht** [comment]
Looks like it is an issue involving cached data in local storage. After the redeployment, the cached info for Lure no longers plays nice with the updated Spirit Aspect. Clearing my local storage resolved the issue on my end (i'd expect that clearing cached data would have the same effect, but can't verify).

**Comment by SteveBallantine** [comment]
Apologies, I pushed a change out without trying it first.
I've reverted now, so everything should be running fine.

Should be able to get this sorted properly in the next day or two.

**Comment by josephlambrecht** [comment]
FYI Steve, everything did work as expected once I cleared my browsing history/cached data in my browser.
